# Generated by Django 5.1.3 on 2024-12-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
